name: Reused Workflow File

on:
  workflow_call:
    inputs:
      name_param:
        required: true
        type: string  # Change 'String' to 'string'

jobs:
  reused_job_implementation:
    runs-on: ubuntu-latest
    steps:
      - name: Implementing reused data
        run: |
          echo "Input parameter: ${{ inputs.name_param }}"
          echo "Executed successfully"
