name: conditional_expression
on: [push]
jobs:
  checking_conditions:
    runs-on: ubuntu-latest
    steps:
      - name: checking if conditions
        if: contains("ashish","his")
        run: echo "IT contains ashish"