name: dependent-jobs

on:
  push:
jobs:
  job1:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - name: Executing Job 1
        run: echo "job1 executed"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Executing Job 2
        run: echo "job2 executed"
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Executing Job 3
        run: echo "job3 executed"    