name: manualCommandTrigger
on:
  workflow_dispatch:
    inputs:
     name:
      description: What is your name
      required: true
      type: String
      
  jobs:
    manualCommandJob:
    runs-on: ubuntu-latest
    steps:
      - name: manual step using command
        runs: echo "${{input.name}}"
