name: run scripts under workflow
on:
  push:
jobs:
  job1:
    defaults:
      run:
        working-directory: ./GitHubActionPractice/.github/workflows/scripts
    runs-on: ubuntu-latest
    steps:
      - name: running scripts
        run: /scriptexe.sh 